version: '3.4'

services:

  cabinet:
    container_name: cabinet
    image: cabinet:latest
    restart: always
    volumes:
      - ./docker/conf/config.json:/usr/share/nginx/html/assets/config.json
      - ./docker/conf/cabinet.conf:/etc/nginx/conf.d/frontend.conf
    networks:
      - frontend


  backend:
    container_name: backend
    image: backend:latest
    restart: always
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASS: 12345
    ports:
      - 8080:8080
    networks:
      - backend

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: acceptance
    ports:
      - 5432:5432
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  backend:

volumes:
  postgres_data:
    name: acceptance-postgres
