FROM node:lts-alpine as builder
WORKDIR /app
COPY ./frontend/ .
RUN npm install
RUN npm run build-cabinet

FROM nginx:latest as cabinet
COPY --from=builder /app/dist/cabinet /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
EXPOSE 80
EXPOSE 443
CMD ["nginx", "-g", "daemon off;"]
